name: CI-MAIN

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
      
    - name: Install node modules
      run: |
        cd front-end
        npm install
        
    - name: Cache
      uses: actions/cache@v2.1.0
      with:
        path: node_modules
        key: front-end-node-modules
      
    - name: Build front-end
      run: |
        cd front-end
        npm run build
      
    - uses: actions/upload-artifact@v2.1.3
      with:
        name: front-end
        path: dist
        
        
